name: "Check flake"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220303_b09baf6/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Check flake format
      run: nix flake check
